Repository Co-TLin/MediaService-backend, pull requests merged in 2021-12, with the labels that each got.

#29 Fix attribute user_id in Profile Table
  src/main/kotlin/com/mediaservice/domain/Profile.kt
Labels: bug, develop

#30 feat: Implement findById of Media, MediaGroupInfo, MediaGroup
  src/main/kotlin/com/mediaservice/application/MediaSeriesService.kt
  src/main/kotlin/com/mediaservice/application/MediaService.kt
  src/main/kotlin/com/mediaservice/application/dto/MediaAllSeriesResponseDto.kt
  src/main/kotlin/com/mediaservice/application/dto/MediaResponseDto.kt
  src/main/kotlin/com/mediaservice/application/dto/MediaSeriesResponseDto.kt
  src/main/kotlin/com/mediaservice/config/SwaggerConfig.kt
  src/main/kotlin/com/mediaservice/domain/Actor.kt
  src/main/kotlin/com/mediaservice/domain/Creator.kt
  src/main/kotlin/com/mediaservice/domain/Genre.kt
  src/main/kotlin/com/mediaservice/domain/Media.kt
  src/main/kotlin/com/mediaservice/domain/MediaAllSeries.kt
  src/main/kotlin/com/mediaservice/domain/MediaSeries.kt
  src/main/kotlin/com/mediaservice/domain/Profile.kt
  src/main/kotlin/com/mediaservice/domain/User.kt
  src/main/kotlin/com/mediaservice/domain/repository/MediaAllSeriesRepository.kt
  src/main/kotlin/com/mediaservice/domain/repository/MediaRepository.kt
  src/main/kotlin/com/mediaservice/domain/repository/MediaSeriesRepository.kt
  src/main/kotlin/com/mediaservice/web/MediaController.kt
  src/main/kotlin/com/mediaservice/web/MediaSeriesController.kt
  src/test/kotlin/com/mediaservice/MediaSeriesServiceTest.kt
  src/test/kotlin/com/mediaservice/MediaServiceTest.kt
Labels: enhancement, develop

#27 feat: implement user create service
  build.gradle.kts
  src/main/kotlin/com/mediaservice/application/UserService.kt
  src/main/kotlin/com/mediaservice/application/dto/UserRequestDto.kt
  src/main/kotlin/com/mediaservice/config/JwtAuthenticationFilter.kt
  src/main/kotlin/com/mediaservice/config/JwtTokenProvider.kt
  src/main/kotlin/com/mediaservice/config/PasswordEncoderConfig.kt
  src/main/kotlin/com/mediaservice/config/SecurityConfig.kt
  src/main/kotlin/com/mediaservice/config/SwaggerConfig.kt
  src/main/kotlin/com/mediaservice/domain/User.kt
  src/main/kotlin/com/mediaservice/domain/repository/UserRepository.kt
  src/main/kotlin/com/mediaservice/exception/BadRequestException.kt
  src/main/kotlin/com/mediaservice/exception/ErrorCode.kt
  src/main/kotlin/com/mediaservice/web/AuthController.kt
  src/main/kotlin/com/mediaservice/web/GlobalControllerAdvice.kt
  src/main/kotlin/com/mediaservice/web/UserController.kt
  src/main/resources/application-local.yml
  src/test/kotlin/com/mediaservice/UserServiceTest.kt
Labels: enhancement, develop

#50 chore: add ktlint to CI & apply ktlint to codes
  .github/workflows/ci.yml
  build.gradle.kts
  src/main/kotlin/com/mediaservice/MediaServiceBackendApplication.kt
  src/main/kotlin/com/mediaservice/application/MediaSeriesService.kt
  src/main/kotlin/com/mediaservice/application/MediaService.kt
  src/main/kotlin/com/mediaservice/application/ProfileService.kt
  src/main/kotlin/com/mediaservice/application/UserService.kt
  src/main/kotlin/com/mediaservice/application/dto/ExceptionDto.kt
  src/main/kotlin/com/mediaservice/application/dto/MediaAllSeriesResponseDto.kt
  src/main/kotlin/com/mediaservice/application/dto/MediaResponseDto.kt
  src/main/kotlin/com/mediaservice/application/dto/MediaSeriesResponseDto.kt
  src/main/kotlin/com/mediaservice/application/dto/ProfileResponseDto.kt
  src/main/kotlin/com/mediaservice/application/dto/UserResponseDto.kt
  src/main/kotlin/com/mediaservice/config/JwtAuthenticationFilter.kt
  src/main/kotlin/com/mediaservice/config/JwtTokenProvider.kt
  src/main/kotlin/com/mediaservice/config/PasswordEncoderConfig.kt
  src/main/kotlin/com/mediaservice/config/SecurityConfig.kt
  src/main/kotlin/com/mediaservice/config/SwaggerConfig.kt
  src/main/kotlin/com/mediaservice/domain/Creator.kt
  src/main/kotlin/com/mediaservice/domain/Genre.kt
  src/main/kotlin/com/mediaservice/domain/MediaAllSeries.kt
  src/main/kotlin/com/mediaservice/domain/MediaSeries.kt
  src/main/kotlin/com/mediaservice/domain/Profile.kt
  src/main/kotlin/com/mediaservice/domain/User.kt
  src/main/kotlin/com/mediaservice/domain/repository/MediaAllSeriesRepository.kt
  src/main/kotlin/com/mediaservice/domain/repository/MediaRepository.kt
  src/main/kotlin/com/mediaservice/domain/repository/MediaSeriesRepository.kt
  src/main/kotlin/com/mediaservice/domain/repository/ProfileRepository.kt
  src/main/kotlin/com/mediaservice/domain/repository/UserRepository.kt
  src/main/kotlin/com/mediaservice/exception/BaseRuntimeException.kt
  src/main/kotlin/com/mediaservice/exception/DataNotFoundException.kt
  src/main/kotlin/com/mediaservice/exception/ErrorCode.kt
  src/main/kotlin/com/mediaservice/web/AuthController.kt
  src/main/kotlin/com/mediaservice/web/GlobalControllerAdvice.kt
  src/main/kotlin/com/mediaservice/web/MediaController.kt
  src/main/kotlin/com/mediaservice/web/MediaSeriesController.kt
  src/main/kotlin/com/mediaservice/web/ProfileController.kt
  src/main/kotlin/com/mediaservice/web/UserController.kt
  src/test/kotlin/com/mediaservice/MediaSeriesServiceTest.kt
  src/test/kotlin/com/mediaservice/MediaServiceTest.kt
  src/test/kotlin/com/mediaservice/ProfileServiceTest.kt
  src/test/kotlin/com/mediaservice/UserServiceTest.kt
Labels: devops, develop

#47 Feat: jwt 안에 사용자 역할 컬럼 추가
  src/main/kotlin/com/mediaservice/application/UserService.kt
  src/main/kotlin/com/mediaservice/config/JwtTokenProvider.kt
  src/main/kotlin/com/mediaservice/domain/User.kt
  src/test/kotlin/com/mediaservice/ProfileServiceTest.kt
  src/test/kotlin/com/mediaservice/UserServiceTest.kt
Labels: refactor, develop

#51 refac: Refactor test code and sign-in sign-up
  build.gradle.kts
  src/main/kotlin/com/mediaservice/application/UserService.kt
  src/main/kotlin/com/mediaservice/application/dto/SignInRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/SignUpRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/UserResponseDto.kt
  src/main/kotlin/com/mediaservice/config/PasswordEncoderConfig.kt
  src/main/kotlin/com/mediaservice/domain/User.kt
  src/main/kotlin/com/mediaservice/domain/repository/UserRepository.kt
  src/main/kotlin/com/mediaservice/web/AuthController.kt
  src/test/kotlin/com/mediaservice/MediaSeriesServiceTest.kt
  src/test/kotlin/com/mediaservice/MediaServiceTest.kt
  src/test/kotlin/com/mediaservice/ProfileServiceTest.kt
  src/test/kotlin/com/mediaservice/UserServiceTest.kt
Labels: refactor, develop

#48 Feat/validation
  build.gradle.kts
  src/main/kotlin/com/mediaservice/application/ProfileService.kt
  src/main/kotlin/com/mediaservice/application/UserService.kt
  src/main/kotlin/com/mediaservice/config/SecurityConfig.kt
  src/main/kotlin/com/mediaservice/exception/ErrorCode.kt
  src/main/kotlin/com/mediaservice/web/GlobalControllerAdvice.kt
Labels: enhancement, develop
