Repository Co-TLin/MediaService-backend, pull requests merged in 2022-03, with the labels that each got.

#140 feat: implement actor, creator, genre delete
  src/main/kotlin/com/mediaservice/application/ActorService.kt
  src/main/kotlin/com/mediaservice/application/CreatorService.kt
  src/main/kotlin/com/mediaservice/application/GenreService.kt
  src/main/kotlin/com/mediaservice/application/validator/IsDeletedValidator.kt
  src/main/kotlin/com/mediaservice/domain/repository/ActorRepository.kt
  src/main/kotlin/com/mediaservice/domain/repository/CreatorRepository.kt
  src/main/kotlin/com/mediaservice/domain/repository/GenreRepository.kt
  src/main/kotlin/com/mediaservice/web/ActorController.kt
  src/main/kotlin/com/mediaservice/web/CreatorController.kt
  src/main/kotlin/com/mediaservice/web/GenreController.kt
  src/test/kotlin/com/mediaservice/ActorServiceTest.kt
  src/test/kotlin/com/mediaservice/CreatorServiceTest.kt
  src/test/kotlin/com/mediaservice/GenreServiceTest.kt
Labels: enhancement, develop

#141 feat: MediaContents Create
  src/main/kotlin/com/mediaservice/application/CreatorService.kt
  src/main/kotlin/com/mediaservice/application/GenreService.kt
  src/main/kotlin/com/mediaservice/application/MediaContentsService.kt
  src/main/kotlin/com/mediaservice/application/dto/media/MediaContentsCreateRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/media/MediaContentsResponseDto.kt
  src/main/kotlin/com/mediaservice/application/dto/media/MediaSeriesCreateRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/user/LikeResponseDto.kt
  src/main/kotlin/com/mediaservice/config/RoleSecurityConfig.kt
  src/main/kotlin/com/mediaservice/domain/MediaContents.kt
  src/main/kotlin/com/mediaservice/domain/MediaSeries.kt
  src/main/kotlin/com/mediaservice/domain/repository/MediaContentsRepository.kt
  src/main/kotlin/com/mediaservice/domain/repository/MediaSeriesRepository.kt
  src/main/kotlin/com/mediaservice/infrastructure/AppInitiator.kt
  src/main/kotlin/com/mediaservice/web/MediaContentsController.kt
  src/test/kotlin/com/mediaservice/MediaContentsServiceTest.kt
Labels: enhancement, develop

#143 fix: Bug fix when access token is null
  src/main/kotlin/com/mediaservice/config/JwtAuthenticationFilter.kt
Labels: develop, fix

#142 feat: Delete media by media id
  build.gradle.kts
  src/main/kotlin/com/mediaservice/application/MediaService.kt
  src/main/kotlin/com/mediaservice/config/RoleSecurityConfig.kt
  src/main/kotlin/com/mediaservice/domain/repository/MediaRepository.kt
  src/main/kotlin/com/mediaservice/web/MediaController.kt
  src/test/kotlin/com/mediaservice/MediaServiceTest.kt
Labels: enhancement, develop

#144 feat: Delete media contents by id
  src/main/kotlin/com/mediaservice/application/MediaContentsService.kt
  src/main/kotlin/com/mediaservice/application/dto/common/ExceptionDto.kt
  src/main/kotlin/com/mediaservice/config/RoleAuthenticationFilter.kt
  src/main/kotlin/com/mediaservice/config/RoleSecurityConfig.kt
  src/main/kotlin/com/mediaservice/domain/repository/MediaContentsRepository.kt
  src/main/kotlin/com/mediaservice/domain/repository/MediaSeriesRepository.kt
  src/main/kotlin/com/mediaservice/web/GlobalControllerAdvice.kt
  src/main/kotlin/com/mediaservice/web/MediaContentsController.kt
  src/main/kotlin/com/mediaservice/web/MediaController.kt
  src/test/kotlin/com/mediaservice/MediaContentsServiceTest.kt
Labels: enhancement, develop

#146 feat: Update media
  src/main/kotlin/com/mediaservice/application/ActorService.kt
  src/main/kotlin/com/mediaservice/application/CreatorService.kt
  src/main/kotlin/com/mediaservice/application/GenreService.kt
  src/main/kotlin/com/mediaservice/application/MediaService.kt
  src/main/kotlin/com/mediaservice/application/ProfileService.kt
  src/main/kotlin/com/mediaservice/application/UserService.kt
  src/main/kotlin/com/mediaservice/application/dto/media/MediaUpdateRequestDto.kt
  src/main/kotlin/com/mediaservice/domain/Media.kt
  src/main/kotlin/com/mediaservice/domain/repository/MediaRepository.kt
  src/main/kotlin/com/mediaservice/web/MediaController.kt
  src/test/kotlin/com/mediaservice/MediaServiceTest.kt
  src/test/kotlin/com/mediaservice/UserServiceTest.kt
Labels: enhancement, develop

#147 feat: Update media series
  build.gradle.kts
  src/main/kotlin/com/mediaservice/application/MediaContentsService.kt
  src/main/kotlin/com/mediaservice/application/MediaService.kt
  src/main/kotlin/com/mediaservice/application/UserService.kt
  src/main/kotlin/com/mediaservice/application/dto/media/MediaSeriesUpdateRequestDto.kt
  src/main/kotlin/com/mediaservice/domain/MediaSeries.kt
  src/main/kotlin/com/mediaservice/domain/repository/MediaRepository.kt
  src/main/kotlin/com/mediaservice/domain/repository/MediaSeriesRepository.kt
  src/main/kotlin/com/mediaservice/infrastructure/PasswordGenerator.kt
  src/main/kotlin/com/mediaservice/web/MediaContentsController.kt
  src/test/kotlin/com/mediaservice/MediaContentsServiceTest.kt
  src/test/kotlin/com/mediaservice/MediaServiceTest.kt
Labels: enhancement, develop

#149 feat: MediaContents Update
  src/main/kotlin/com/mediaservice/application/MediaContentsService.kt
  src/main/kotlin/com/mediaservice/application/dto/media/MediaContentsUpdateRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/media/MediaSeriesCreateRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/media/MediaSeriesUpdateRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/media/MediaUpdateRequestDto.kt
  src/main/kotlin/com/mediaservice/domain/MediaContents.kt
  src/main/kotlin/com/mediaservice/domain/repository/MediaContentsRepository.kt
  src/main/kotlin/com/mediaservice/web/MediaContentsController.kt
  src/test/kotlin/com/mediaservice/MediaContentsServiceTest.kt
Labels: enhancement, develop

#155 refac: Add dto validation
  build.gradle.kts
  src/main/kotlin/com/mediaservice/application/dto/media/ActorCreateRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/media/ActorUpdateRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/media/CreatorCreateRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/media/CreatorUpdateRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/media/GenreCreateRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/media/GenreUpdateRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/media/MediaContentsCreateRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/media/MediaContentsUpdateRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/media/MediaSeriesCreateRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/media/MediaSeriesUpdateRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/media/MediaUpdateRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/user/PasswordFindRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/user/PasswordUpdateRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/user/ProfileCreateRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/user/ProfileUpdateRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/user/SignInRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/user/SignUpRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/user/SignUpVerifyAuthRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/user/SignUpVerifyMailRequestDto.kt
  src/main/kotlin/com/mediaservice/web/ActorController.kt
  src/main/kotlin/com/mediaservice/web/AuthController.kt
  src/main/kotlin/com/mediaservice/web/CreatorController.kt
  src/main/kotlin/com/mediaservice/web/GenreController.kt
  src/main/kotlin/com/mediaservice/web/MediaContentsController.kt
  src/main/kotlin/com/mediaservice/web/MediaController.kt
  src/main/kotlin/com/mediaservice/web/ProfileController.kt
  src/main/kotlin/com/mediaservice/web/UserController.kt
Labels: refactor, develop

#150 feat: create Media
  src/main/kotlin/com/mediaservice/application/MediaContentsService.kt
  src/main/kotlin/com/mediaservice/application/MediaService.kt
  src/main/kotlin/com/mediaservice/application/dto/media/MediaCreateRequestDto.kt
  src/main/kotlin/com/mediaservice/domain/Media.kt
  src/main/kotlin/com/mediaservice/domain/repository/MediaRepository.kt
  src/main/kotlin/com/mediaservice/web/MediaController.kt
  src/test/kotlin/com/mediaservice/MediaServiceTest.kt
Labels: enhancement, develop

#123 Feat/55
  src/main/kotlin/com/mediaservice/application/WishContentService.kt
  src/main/kotlin/com/mediaservice/domain/repository/WishContentRepository.kt
  src/main/kotlin/com/mediaservice/infrastructure/AppInitiator.kt
  src/main/kotlin/com/mediaservice/web/WishContentController.kt
  src/test/kotlin/com/mediaservice/WishContentServiceTest.kt
Labels: enhancement, develop

#124 Feat/106
  src/main/kotlin/com/mediaservice/application/WishContentService.kt
  src/main/kotlin/com/mediaservice/domain/repository/WishContentRepository.kt
  src/main/kotlin/com/mediaservice/web/WishContentController.kt
  src/test/kotlin/com/mediaservice/WishContentServiceTest.kt
Labels: enhancement, develop

#158 feat: Implement Create & Delete of MediaContents-[Actor, Creator, Genre]
  src/main/kotlin/com/mediaservice/application/MediaContentsService.kt
  src/main/kotlin/com/mediaservice/application/dto/media/MediaContentsActorRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/media/MediaContentsCreatorRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/media/MediaContentsGenreRequestDto.kt
  src/main/kotlin/com/mediaservice/domain/MediaContents.kt
  src/main/kotlin/com/mediaservice/domain/MediaContentsActor.kt
  src/main/kotlin/com/mediaservice/domain/MediaContentsCreator.kt
  src/main/kotlin/com/mediaservice/domain/MediaContentsGenre.kt
  src/main/kotlin/com/mediaservice/domain/repository/MediaContentsActorRepository.kt
  src/main/kotlin/com/mediaservice/domain/repository/MediaContentsCreatorRepository.kt
  src/main/kotlin/com/mediaservice/domain/repository/MediaContentsGenreRepository.kt
  src/main/kotlin/com/mediaservice/web/MediaContentsController.kt
  src/test/kotlin/com/mediaservice/MediaContentsServiceTest.kt
Labels: enhancement, develop

#161 refac: Refactor wish contents service and like media contents
  src/main/kotlin/com/mediaservice/application/ProfileService.kt
  src/main/kotlin/com/mediaservice/application/WishContentService.kt
  src/main/kotlin/com/mediaservice/application/dto/user/LikeRequestDto.kt
  src/main/kotlin/com/mediaservice/domain/repository/WishContentRepository.kt
  src/main/kotlin/com/mediaservice/web/ProfileController.kt
  src/main/kotlin/com/mediaservice/web/WishContentController.kt
  src/test/kotlin/com/mediaservice/ProfileServiceTest.kt
  src/test/kotlin/com/mediaservice/WishContentServiceTest.kt
Labels: refactor, develop

#160 feat: Implement findAll of Actor, Creator and Genre (#130)
  src/main/kotlin/com/mediaservice/application/ActorService.kt
  src/main/kotlin/com/mediaservice/application/CreatorService.kt
  src/main/kotlin/com/mediaservice/application/GenreService.kt
  src/main/kotlin/com/mediaservice/domain/repository/ActorRepository.kt
  src/main/kotlin/com/mediaservice/domain/repository/CreatorRepository.kt
  src/main/kotlin/com/mediaservice/domain/repository/GenreRepository.kt
  src/main/kotlin/com/mediaservice/web/ActorController.kt
  src/main/kotlin/com/mediaservice/web/CreatorController.kt
  src/main/kotlin/com/mediaservice/web/GenreController.kt
  src/test/kotlin/com/mediaservice/ActorServiceTest.kt
  src/test/kotlin/com/mediaservice/CreatorServiceTest.kt
  src/test/kotlin/com/mediaservice/GenreServiceTest.kt
Labels: enhancement, develop
