Repository Co-TLin/MediaService-backend, pull requests merged in 2022-01, with the labels that each got.

#60 fix: Fix bug in sign-up
  src/main/kotlin/com/mediaservice/domain/repository/UserRepository.kt
Labels: develop, fix

#52 feat: Implement Actor, Genre, Creator create
  src/main/kotlin/com/mediaservice/MediaServiceBackendApplication.kt
  src/main/kotlin/com/mediaservice/application/ActorService.kt
  src/main/kotlin/com/mediaservice/application/CreatorService.kt
  src/main/kotlin/com/mediaservice/application/GenreService.kt
  src/main/kotlin/com/mediaservice/application/MediaService.kt
  src/main/kotlin/com/mediaservice/application/dto/ActorCreateRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/ActorResponseDto.kt
  src/main/kotlin/com/mediaservice/application/dto/CreatorCreateRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/CreatorResponseDto.kt
  src/main/kotlin/com/mediaservice/application/dto/GenreCreateRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/GenreResponseDto.kt
  src/main/kotlin/com/mediaservice/application/dto/MediaResponseDto.kt
  src/main/kotlin/com/mediaservice/domain/Actor.kt
  src/main/kotlin/com/mediaservice/domain/Creator.kt
  src/main/kotlin/com/mediaservice/domain/Genre.kt
  src/main/kotlin/com/mediaservice/domain/Media.kt
  src/main/kotlin/com/mediaservice/domain/repository/ActorRepository.kt
  src/main/kotlin/com/mediaservice/domain/repository/CreatorRepository.kt
  src/main/kotlin/com/mediaservice/domain/repository/GenreRepository.kt
  src/main/kotlin/com/mediaservice/exception/ErrorCode.kt
  src/main/kotlin/com/mediaservice/web/ActorController.kt
  src/main/kotlin/com/mediaservice/web/CreatorController.kt
  src/main/kotlin/com/mediaservice/web/GenreController.kt
  src/test/kotlin/com/mediaservice/ActorServiceTest.kt
  src/test/kotlin/com/mediaservice/CreatorServiceTest.kt
  src/test/kotlin/com/mediaservice/GenreServiceTest.kt
  src/test/kotlin/com/mediaservice/MediaSeriesServiceTest.kt
  src/test/kotlin/com/mediaservice/MediaServiceTest.kt
Labels: enhancement, develop

#61 feat: Implement validator chain
  gradlew.bat
  src/main/kotlin/com/mediaservice/application/ActorService.kt
  src/main/kotlin/com/mediaservice/application/CreatorService.kt
  src/main/kotlin/com/mediaservice/application/GenreService.kt
  src/main/kotlin/com/mediaservice/application/UserService.kt
  src/main/kotlin/com/mediaservice/application/validator/IsDeletedValidator.kt
  src/main/kotlin/com/mediaservice/application/validator/PasswordValidator.kt
  src/main/kotlin/com/mediaservice/application/validator/Validator.kt
  src/main/kotlin/com/mediaservice/domain/Actor.kt
  src/main/kotlin/com/mediaservice/domain/Creator.kt
  src/main/kotlin/com/mediaservice/domain/Genre.kt
Labels: enhancement, develop

#90 Refactor: findByUserId for Profile
  src/main/kotlin/com/mediaservice/domain/Profile.kt
  src/main/kotlin/com/mediaservice/domain/repository/ProfileRepository.kt
  src/test/kotlin/com/mediaservice/ProfileServiceTest.kt
Labels: refactor, develop

#82 feat: implement email service
  .gitignore
  build.gradle.kts
  src/main/kotlin/com/mediaservice/application/UserService.kt
  src/main/kotlin/com/mediaservice/config/ApplicationConfig.kt
  src/main/kotlin/com/mediaservice/config/EmailProperties.kt
  src/main/kotlin/com/mediaservice/web/UserController.kt
  src/main/resources/application-local.yml
  src/test/kotlin/com/mediaservice/UserServiceTest.kt
Labels: enhancement, develop

#92 feat: implement Update User Password
  src/main/kotlin/com/mediaservice/application/UserService.kt
  src/main/kotlin/com/mediaservice/application/dto/user/PasswordUpdateRequestDto.kt
  src/main/kotlin/com/mediaservice/application/validator/PasswordFormatValidator.kt
  src/main/kotlin/com/mediaservice/domain/User.kt
  src/main/kotlin/com/mediaservice/domain/repository/UserRepository.kt
  src/main/kotlin/com/mediaservice/web/UserController.kt
  src/main/resources/application-local.yml
  src/test/kotlin/com/mediaservice/UserServiceTest.kt
Labels: enhancement, develop

#96 feat: Implement Find User Password
  src/main/kotlin/com/mediaservice/application/PasswordGenerator.kt
  src/main/kotlin/com/mediaservice/application/UserService.kt
  src/main/kotlin/com/mediaservice/application/dto/user/PasswordFindRequestDto.kt
  src/main/kotlin/com/mediaservice/application/infrastructure/GoogleMailSender.kt
  src/main/kotlin/com/mediaservice/config/ApplicationConfig.kt
  src/main/kotlin/com/mediaservice/exception/ErrorCode.kt
  src/main/kotlin/com/mediaservice/exception/InternalServerException.kt
  src/main/kotlin/com/mediaservice/exception/ServerUnavailableException.kt
  src/main/kotlin/com/mediaservice/web/AuthController.kt
  src/main/kotlin/com/mediaservice/web/GlobalControllerAdvice.kt
  src/test/kotlin/com/mediaservice/UserServiceTest.kt
Labels: enhancement, develop
