Repository Co-TLin/MediaService-backend, pull requests merged in 2022-02, with the labels that each got.

#97 Feat/44
  src/main/kotlin/com/mediaservice/application/ProfileService.kt
  src/main/kotlin/com/mediaservice/application/dto/user/ProfileResponseDto.kt
  src/main/kotlin/com/mediaservice/domain/Profile.kt
  src/main/kotlin/com/mediaservice/domain/repository/ProfileRepository.kt
  src/main/kotlin/com/mediaservice/web/ProfileController.kt
  src/test/kotlin/com/mediaservice/ProfileServiceTest.kt
Labels: enhancement, develop

#91 Feature/36
  src/main/kotlin/com/mediaservice/application/ProfileService.kt
  src/main/kotlin/com/mediaservice/application/dto/user/ProfileCreateRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/user/ProfileResponseDto.kt
  src/main/kotlin/com/mediaservice/application/validator/ProfileNumberValidator.kt
  src/main/kotlin/com/mediaservice/domain/Profile.kt
  src/main/kotlin/com/mediaservice/domain/repository/ProfileRepository.kt
  src/main/kotlin/com/mediaservice/exception/ErrorCode.kt
  src/main/kotlin/com/mediaservice/web/ProfileController.kt
  src/test/kotlin/com/mediaservice/ProfileServiceTest.kt
Labels: enhancement, develop

#101 feat: Implement user is duplicated by email
  src/main/kotlin/com/mediaservice/application/UserService.kt
  src/main/kotlin/com/mediaservice/web/UserController.kt
  src/test/kotlin/com/mediaservice/UserServiceTest.kt
Labels: enhancement, develop

#99 refac: Refactor for sprint 1
  .github/workflows/ci.yml
  src/main/kotlin/com/mediaservice/application/ActorService.kt
  src/main/kotlin/com/mediaservice/application/CreatorService.kt
  src/main/kotlin/com/mediaservice/application/GenreService.kt
  src/main/kotlin/com/mediaservice/application/PasswordGenerator.kt
  src/main/kotlin/com/mediaservice/application/ProfileService.kt
  src/main/kotlin/com/mediaservice/application/UserService.kt
  src/main/kotlin/com/mediaservice/application/dto/common/ExceptionDto.kt
  src/main/kotlin/com/mediaservice/application/dto/user/ProfileResponseDto.kt
  src/main/kotlin/com/mediaservice/application/dto/user/SignInProfileResponseDto.kt
  src/main/kotlin/com/mediaservice/application/dto/user/SignInResponseDto.kt
  src/main/kotlin/com/mediaservice/application/infrastructure/GoogleMailSender.kt
  src/main/kotlin/com/mediaservice/application/validator/UserEqualValidator.kt
  src/main/kotlin/com/mediaservice/config/SecurityConfig.kt
  src/main/kotlin/com/mediaservice/domain/Actor.kt
  src/main/kotlin/com/mediaservice/domain/Creator.kt
  src/main/kotlin/com/mediaservice/domain/Genre.kt
  src/main/kotlin/com/mediaservice/domain/Profile.kt
  src/main/kotlin/com/mediaservice/exception/ErrorCode.kt
  src/main/kotlin/com/mediaservice/exception/UnauthorizedException.kt
  src/main/kotlin/com/mediaservice/infrastructure/GoogleMailSender.kt
  src/main/kotlin/com/mediaservice/web/AuthController.kt
  src/main/kotlin/com/mediaservice/web/GlobalControllerAdvice.kt
  src/main/kotlin/com/mediaservice/web/ProfileController.kt
  src/main/kotlin/com/mediaservice/web/UserController.kt
  src/test/kotlin/com/mediaservice/ProfileServiceTest.kt
  src/test/kotlin/com/mediaservice/UserServiceTest.kt
Labels: enhancement, refactor, develop

#109 feat: redis connection
  build.gradle.kts
  docker-compose.yml
  src/main/kotlin/com/mediaservice/config/RedisConfig.kt
  src/main/resources/application-local.yml
Labels: enhancement, develop

#111 Feat: create refreshToken
  src/main/kotlin/com/mediaservice/application/UserService.kt
  src/main/kotlin/com/mediaservice/application/dto/user/SignInResponseDto.kt
  src/main/kotlin/com/mediaservice/config/JwtAuthenticationEntryPoint.kt
  src/main/kotlin/com/mediaservice/config/JwtAuthenticationFilter.kt
  src/main/kotlin/com/mediaservice/config/JwtTokenProvider.kt
  src/main/kotlin/com/mediaservice/config/RoleAuthenticationFilter.kt
  src/main/kotlin/com/mediaservice/domain/RefreshToken.kt
  src/main/kotlin/com/mediaservice/domain/repository/RefreshTokenRepository.kt
  src/main/resources/application-local.yml
  src/test/kotlin/com/mediaservice/UserServiceTest.kt
Labels: enhancement, develop

#113 feat: implement PageableFactory
  src/main/kotlin/com/mediaservice/application/dto/media/MediaAllSeriesResponseDto.kt
  src/main/kotlin/com/mediaservice/infrastructure/Page.kt
  src/main/kotlin/com/mediaservice/infrastructure/PageRequest.kt
Labels: enhancement, develop

#116 fix: Fix role security config
  docker-compose.yml
  src/main/kotlin/com/mediaservice/config/JwtAuthenticationFilter.kt
  src/main/kotlin/com/mediaservice/config/JwtTokenProvider.kt
  src/main/kotlin/com/mediaservice/config/RoleAuthenticationFilter.kt
  src/main/kotlin/com/mediaservice/config/RoleSecurityConfig.kt
  src/main/kotlin/com/mediaservice/config/SecurityConfig.kt
  src/main/resources/application-local.yml
Labels: develop, fix

#117 feat: implement create like
  src/main/kotlin/com/mediaservice/application/ProfileService.kt
  src/main/kotlin/com/mediaservice/application/dto/media/MediaAllSeriesResponseDto.kt
  src/main/kotlin/com/mediaservice/application/dto/user/LikeRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/user/LikeResponseDto.kt
  src/main/kotlin/com/mediaservice/config/JwtTokenProvider.kt
  src/main/kotlin/com/mediaservice/domain/Like.kt
  src/main/kotlin/com/mediaservice/domain/repository/LikeRepository.kt
  src/main/kotlin/com/mediaservice/domain/repository/ProfileRepository.kt
  src/main/kotlin/com/mediaservice/infrastructure/AppInitiator.kt
  src/main/kotlin/com/mediaservice/web/ProfileController.kt
  src/test/kotlin/com/mediaservice/ProfileServiceTest.kt
Labels: enhancement, develop

#118 feat: Implement Delete Like
  src/main/kotlin/com/mediaservice/application/ProfileService.kt
  src/main/kotlin/com/mediaservice/domain/repository/LikeRepository.kt
  src/main/kotlin/com/mediaservice/web/ProfileController.kt
  src/test/kotlin/com/mediaservice/ProfileServiceTest.kt
Labels: enhancement, develop

#120 feat: implement find detail of mediaAllSeries
  src/main/kotlin/com/mediaservice/application/MediaSeriesService.kt
  src/main/kotlin/com/mediaservice/application/dto/media/MediaDetailRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/media/MediaDetailResponseDto.kt
  src/main/kotlin/com/mediaservice/application/dto/media/MediaResponseDto.kt
  src/main/kotlin/com/mediaservice/application/dto/media/MediaSeriesResponseDto.kt
  src/main/kotlin/com/mediaservice/application/validator/RateMatchValidator.kt
  src/main/kotlin/com/mediaservice/domain/Media.kt
  src/main/kotlin/com/mediaservice/domain/MediaAllSeries.kt
  src/main/kotlin/com/mediaservice/domain/MediaSeries.kt
  src/main/kotlin/com/mediaservice/domain/repository/LikeRepository.kt
  src/main/kotlin/com/mediaservice/domain/repository/MediaRepository.kt
  src/main/kotlin/com/mediaservice/domain/repository/MediaSeriesRepository.kt
  src/main/kotlin/com/mediaservice/exception/ErrorCode.kt
  src/main/kotlin/com/mediaservice/infrastructure/AppInitiator.kt
  src/main/kotlin/com/mediaservice/web/MediaSeriesController.kt
  src/test/kotlin/com/mediaservice/MediaSeriesServiceTest.kt
  src/test/kotlin/com/mediaservice/MediaServiceTest.kt
  src/test/kotlin/com/mediaservice/ProfileServiceTest.kt
Labels: enhancement, develop

#121 fix: sign up
  src/main/kotlin/com/mediaservice/application/UserService.kt
  src/main/kotlin/com/mediaservice/application/dto/user/SignUpVerifyAuthRequestDto.kt
  src/main/kotlin/com/mediaservice/application/dto/user/SignUpVerifyMailRequestDto.kt
  src/main/kotlin/com/mediaservice/config/RedisConfig.kt
  src/main/kotlin/com/mediaservice/infrastructure/Authentication.kt
  src/main/kotlin/com/mediaservice/infrastructure/GoogleMailSender.kt
  src/main/kotlin/com/mediaservice/infrastructure/RedisUtil.kt
  src/main/kotlin/com/mediaservice/web/AuthController.kt
  src/test/kotlin/com/mediaservice/UserServiceTest.kt
Labels: enhancement, develop

#126 fix: Bug in is duplicated email and create profile
  src/main/kotlin/com/mediaservice/application/ProfileService.kt
  src/main/kotlin/com/mediaservice/config/SecurityConfig.kt
  src/main/kotlin/com/mediaservice/domain/repository/ProfileRepository.kt
  src/main/kotlin/com/mediaservice/web/ProfileController.kt
  src/main/kotlin/com/mediaservice/web/UserController.kt
  src/test/kotlin/com/mediaservice/ProfileServiceTest.kt
Labels: develop, fix
